from fastapi import FastAPI
from starlette.responses import Response, JSONResponse

from utils.postcard_generator import make_postcard
from utils.system import get_categories, get_postcard_preview, get_postcards_list

app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Postcard generator API"}


@app.get(
    "/preview",
    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses={
        200: {
            "content": {"image/png": {}}
        }
    },
    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=Response
)
async def get_preview(category: str = "say_thanks", template: str = "picture0"):
    image_bytes: bytes = await get_postcard_preview(category, template)
    return Response(content=image_bytes, media_type="image/png")


@app.get("/categories")
async def get_types():
    categories = await get_categories()
    return JSONResponse({"data": categories})


@app.get("/postcards")
async def get_postcards_by_type(category: str = "say_thanks"):
    postcards = await get_postcards_list(category)
    return JSONResponse({"data": postcards})


@app.get(
    "/postcard",
    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses={
        200: {
            "content": {"image/png": {}}
        }
    },
    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=Response
)
async def get_postcard(text: str = "test", category: str = "say_thanks", template: str = "picture0"):
    image_bytes: bytes = await make_postcard(text, category, template)
    return Response(content=image_bytes, media_type="image/png")
